#include <infrarrojo.h>
#define PIN_MOTOR_1_EN 6
#define PIN_MOTOR_1_N1 7
#define PIN_MOTOR_1_N2 5
#define PIN_MOTOR_2_EN 3
#define PIN_MOTOR_2_N3 4
#define PIN_MOTOR_2_N4 2

#define MOTOR_1_STOP digitalWrite(PIN_MOTOR_1_N1,LOW);digitalWrite(PIN_MOTOR_1_N2,LOW)
#define MOTOR_1_FORWARD digitalWrite(PIN_MOTOR_1_N1,LOW);digitalWrite(PIN_MOTOR_1_N2,HIGH)
#define MOTOR_1_BACKWARD digitalWrite(PIN_MOTOR_1_N1,HIGH);digitalWrite(PIN_MOTOR_1_N2,LOW)


#define MOTOR_2_STOP digitalWrite(PIN_MOTOR_2_N3,LOW);digitalWrite(PIN_MOTOR_2_N4,LOW)
#define MOTOR_2_FORWARD digitalWrite(PIN_MOTOR_2_N3,LOW);digitalWrite(PIN_MOTOR_2_N4,HIGH)
#define MOTOR_2_BACKWARD digitalWrite(PIN_MOTOR_2_N3,HIGH);digitalWrite(PIN_MOTOR_2_N4,LOW)

#define CAR_FORWARD MOTOR_1_FORWARD;MOTOR_2_FORWARD
#define CAR_BACKWARD MOTOR_1_BACKWARD;MOTOR_2_BACKWARD
#define CAR_RIGTH MOTOR_1_FORWARD;MOTOR_2_BACKWARD
#define CAR_LEFT MOTOR_1_BACKWARD;MOTOR_2_FORWARD
#define CAR_STOP MOTOR_1_STOP;MOTOR_2_STOP



infrarrojo estado(13);//DEFINICION DEL PIN DEL ARDUINO A USAR
int VALOR;//VARIBLE QUE RECIBE EL DATO
int led =12;//REDEFINICION DE PIN DE ARDUINO PARA LED INDICADOR DE PULSO(ESTO ES OPCIONAL)
int led_estado;//VARIABLE

//#define MOTOR_1_SPEED(_SPEED) analogWrite(PIN_MOTOR_1_EN,_SPEED)
//#define MOTOR_2_SPEED(_SPEED) analogWrite(PIN_MOTOR_1_EN,_SPEED)


void setup() {
  pinMode(PIN_MOTOR_1_EN, OUTPUT);
  pinMode(PIN_MOTOR_1_N1, OUTPUT);
  pinMode(PIN_MOTOR_1_N2, OUTPUT);
  pinMode(PIN_MOTOR_2_EN, OUTPUT);
  pinMode(PIN_MOTOR_2_N3, OUTPUT);
  pinMode(PIN_MOTOR_2_N4, OUTPUT);
  digitalWrite(PIN_MOTOR_1_EN, HIGH);
  digitalWrite(PIN_MOTOR_2_EN, HIGH);

  pinMode(led,OUTPUT);//LED QUE INDICA EL ESTADO DEL LED
  Serial.begin(9600); //VELOCIDAD COMUNICACION SERIAL

}

void loop() {
  led_estado = estado.lectura(VALOR);//LED QUE RECOGE EL ESTADO DEL SENSOR
if(led_estado == 1)//ETAPA DE COMPARACION PARA ACTIVAR UN LED SEGUN EL ESTADO DEL SENSOR
{
  digitalWrite(led,HIGH);//PRENDE UN LED SI EL SENSOR DETECTA OBSTACULO
  CAR_RIGTH;
  delay(100);
}
else
{
  digitalWrite(led,LOW);
  CAR_STOP;
  delay(100);
}






}
